use_frameworks!

platform :ios, '11.0'

target 'PodSpecSDK_Example' do
  pod 'PodSpecSDK', :path => '../'

  target 'PodSpecSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
